pm uninstall -k --user 0 com.miui.daemon
pm uninstall -k --user 0 com.miui.msa.global
pm uninstall -k --user 0 com.xiaomi.joyose
pm uninstall -k --user 0 com.facebook.services
pm uninstall -k --user 0 com.facebook.appmanager
pm uninstall -k --user 0 com.facebook.system
pm uninstall -k --user 0 com.miui.analytics
pm uninstall -k --user 0 com.miui.android.fashiongallery
pm uninstall -k --user 0 com.xiaomi.midrop
pm uninstall -k --user 0 com.android.browser
pm uninstall -k --user 0 com.miui.bugreport
pm uninstall -k --user 0 com.xiaomi.glgm
pm uninstall -k --user 0 com.miui.yellowpage
pm uninstall -k --user 0 com.miui.miservice
pm uninstall -k --user 0 com.miui.player
pm uninstall -k --user 0 com.mipay.wallet.in
pm uninstall -k --user 0 com.xiaomi.payment
pm uninstall -k --user 0 com.miui.hybrid
pm uninstall -k --user 0 com.miui.hybrid.accessory
pm uninstall -k --user 0 com.miui.videoplayer
pm uninstall -k --user 0 com.xiaomi.mipicks
pm uninstall -k --user 0 com.miui.translation.xmcloud
pm uninstall -k --user 0 cn.wps.xiaomi.abroad.lite
pm uninstall -k --user 0 com.miui.global.packageinstaller
pm uninstall -k --user 0 com.micredit.in
pm uninstall -k --user 0 com.android.providers.downloads.ui
pm uninstall -k --user 0 com.mi.android.globalFileexplorer
pm uninstall -k --user 0 com.google.android.videos
pm uninstall -k --user 0 com.google.android.apps.wellbeing
pm uninstall -k --user 0 com.google.android.feedback
pm uninstall -k --user 0 com.google.android.marvin.talkback
pm uninstall -k --user 0 com.miui.calculator
pm uninstall -k --user 0 com.miui.compass
pm uninstall -k --user 0 com.duokan.phone.remotecontroller
pm uninstall -k --user 0 com.xiaomi.scanner
pm uninstall -k --user 0 com.google.android.apps.subscriptions.red
pm uninstall -k --user 0 com.miui.notes
pm uninstall -k --user 0 com.android.thememanager
pm uninstall -k --user 0 com.miui.micloudsync
pm uninstall -k --user 0 com.miui.easygo
pm uninstall -k --user 0 com.miui.cloudbackup
pm uninstall -k --user 0 com.miui.cloudservice
pm uninstall -k --user 0 com.xiaomi.micloud.sdk
pm uninstall -k --user 0 com.xiaomi.mi_connect_service
pm uninstall -k --user 0 com.xiaomi.xmsf
pm uninstall -k --user 0 com.miui.mishare.connectivity
pm uninstall -k --user 0 com.miui.cleaner
pm uninstall -k --user 0 com.xiaomi.account
